<div style="padding: 0px 30px 30px 30px;">
	<div><img src="/images/mnu_ct.png" style="float:left;width:150px;padding-right:10px;"/>
	<div><h3>La communauté des Aloïstes</h3>
	<p>Les Aloïstes ? Ce sont les membres d'Aloa, comme vous et nous, et vous pouvez tous les retrouver ici. 
	N'hésitez pas à visiter les pages des membres pour mieux les connaitre et échanger.</p>
	
	</div>
	</div>

			<div id="trombinoscope">
				
				
				<?php
				
				$this->partialLoop()->setObjectKey('model');
				echo $this->partialLoop("p_trombinoscope.phtml", $this->trombi);
				
				?>


				
				<div class="c_left"></div>
				</div>
				
<!--  FIN Trombinoscope -->

	<h5>Rechercher</h5>
	<p>Grâce au moteur de recherche vous pouvez rechercher des membres par leur nom, mais aussi en entrant simplement un mot, vous retrouverez tous les membres qui l'utilisent sur leur page personnelle.</p>
	<div>
	<form name="recherche_form" method='post' action="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'search'),'default',true); ?>">
	<p><input name="rqt" style="width:300px"/></p>
	<input type="submit" value="Rechercher"/>
	</form>
	<br/>
	</div>

	
	<div><a name="advices"></a>
		<h3><img src="/images/conseil.png" style="padding-bottom:10px"> Les conseils pratiques de la communauté</h3>
		
		<p>
		Au fil des discussions, des témoignages, des questions c'est une mine d'or de conseils pratiques et d'astuces qui est constituée par les membres d'Aloa. Vous pouvez retrouvez ici toutes les contributions que les membres ont marqué comme conseils pratiques. Participer vous aussi lors de vos visites en indiquant les contributions qui vous ont été les plus utiles par un <img src="/images/conseil.png">.
		</p>
		
		<!--
		<h5>Classés par thème :</h5>
				<div style="margin-left:15px;padding-bottom:15px;">
				<a href="#"><b>Non classés</b></a>,&nbsp;<a href="#">intéressant</a>,&nbsp;<a href="#">conseils pratiques</a>,&nbsp;<a href="#">Associations/Organisations</a>
				</div>
		-->
		<h5>Classés par type de contribution :</h5>
				<div style="margin-left:15px;padding-bottom:15px;">
				
				<a href="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'index'),'default',true); ?>#advices"<?php echo ($this->type_filter==null)?"class='arial_b'":''; ?>>Tous</a>,&nbsp;
				<a href="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'index', 'type' => 'document'),'default',true); ?>#advices"<?php echo ($this->type_filter=='document')?"class='arial_b'":''; ?>>Documents</a>,&nbsp;
				<a href="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'index', 'type' => 'qr'),'default',true); ?>#advices"<?php echo ($this->type_filter=='qr')?"class='arial_b'":''; ?>>Questions & Réponses</a>,&nbsp;
				<a href="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'index', 'type' => 'story'),'default',true); ?>#advices"<?php echo ($this->type_filter=='story')?"class='arial_b'":''; ?>>Témoignages</a>,&nbsp;
				<!--<a href="#">Bavardages</a>,&nbsp;-->
				<a href="<?php echo $this->url(array('controller'=>'communaute', 'action' => 'index', 'type' => 'pgperso'),'default',true); ?>#advices"<?php echo ($this->type_filter=='pgperso')?"class='arial_b'":''; ?>>Pages personnelles</a>
				</div>
		
		<div class="evtlist">
		
		
					<?php 
						if(count($this->advices) > 0){
							
							echo $this->partial("p_contrib_events.phtml", array('contribs' => $this->advices, 'disp_type' => 1, 'disp_user' => 1));
						}else if($this->advices == null){
							echo "<p class='errors'>Les conseils pratiques sont temporairement indisponibles. Nous faisons de motre mieux pour rétablir la situation le plus rapidement possible. Merci.</p>";
						}else{
							echo "<p>Personne n'a encore marquer comme conseil pratique une contribution de cette catégorie.</p>";
						}
						//print_r($this->advices);
					?>
		

		</div>
		
	
	</div>

				<div class="lrgspc"></div>
				<div class="lrgspc"></div>

</div>