

<div style="text-align:left;font-size:10pt;overflow:auto;">
<h4><img src="/images/mnu_contrib_sml.png"/> Les bavardages de la page : <em><?php echo $this->ttl; ?></em></h4>
<div id="bavardages" style="background:#FFF;border:2px solid black;height:400px;overflow:auto;">

	<div id="bvrdg_31" style="background:#EEE;">
		
		<a name="id_bvrdg_31"></a>
		<div id="bvrdg_310" style="border-top:2px solid #CCC;border-bottom:2px solid #CCC;">
			<div style="padding:2px;width:72px;float:left;">
			
			<div class="f_left" style="padding-bottom:1px;">
			<a class="info_profil" href="#" title="Consulter la dernière contribution de Jeanne"><span><img src="/images/avtr_nnrs_red.png" class="sml_avtr"/>
			<img src="/images/aidant.png" title="Aidant"><font class="arial_b">Jeanne, Troyes (10000)</font><br/><p>
			<em>""</em></p>inscrit depuis le 30/06/09</span><img src="/images/avtr_nnrs_red.png" class="sml_avtr"/></a></div>
			<div class="f_left" style="padding-bottom:1px;">
			<a class="info_profil" href="#" title="Consulter la dernière contribution de Arno10">
			<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
			&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="sml_avtr"/></a></div> 
			<div class="f_left" style="padding-bottom:1px;">
			<a class="info_profil" href="#" title="Consulter la dernière contribution de Chrstophe"><span><img src="/images/avtr_rolreg.png" class="sml_avtr"/>
			<img src="/images/supporter.png" title="Supporter"><font class="arial_b">Christophe, Saint André les Vergers (10120)</font><br/><p>
			<em>""</em></p>inscrit depuis le 20/07/09</span><img src="/images/avtr_rolreg.png" class="sml_avtr"/></a></div>
			<div class="f_left" style="padding-bottom:1px;">
			<a class="info_profil" href="#" title="Consulter la dernière contribution de Camille"><span><img src="/images/avtr_nnrs_green.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant"><font class="arial_b">Camille, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 25/06/09</span><img src="/images/avtr_nnrs_green.png" class="sml_avtr"/></a></div>
			
			</div>
			
			<div style="font-family:arial;padding:2px;height:95px;overflow:auto;">
			<div style="float:right;">
			<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
			</div>
			<font class="arial_b">Bonjour tout le monde</font><br/>
			dernière contribution <br/>il y a 3 heures, de <a href="#" title="Consulter la dernière contribution de Georges">
			Arno10</a>
			<p>
			<a href="javascript:void(0);" onClick="javascript:(document.getElementById('bvrdg_31_content').className == 'bvrdg_expanded')?changeStyle('bvrdg_31_content','bvrdg_minimized'):changeStyle('bvrdg_31_content','bvrdg_expanded');(document.getElementById('bvrdg_31_expander').className == 'bvrdg_expand')?changeStyle('bvrdg_31_expander','bvrdg_minimize'):changeStyle('bvrdg_31_expander','bvrdg_expand');">Voir ce bavardage</a></p>
			</div>
			
		</div>

		<div id="bvrdg_31_content" class="bvrdg_minimized">	
<!-- reprise de l'expander pour simplifier le contrôle -->		
<a href="javascript:void(0);" onClick="javascript:changeStyle('bvrdg_31_content','bvrdg_minimized');changeStyle('bvrdg_31_expander','bvrdg_expand');"><div id="bvrdg_31_expander_bis" class="bvrdg_minimize">
			</div></a>
		
		
			<div id="bvrdg_311" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
						<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Jeanne"><span><img src="/images/avtr_nnrs_red.png" class="sml_avtr"/>
					<img src="/images/aidant.png" title="Aidant"><font class="arial_b">Jeanne, Troyes (10000)</font><br/><p>
					<em>""</em></p>inscrit depuis le 30/06/09</span><img src="/images/avtr_nnrs_red.png" class="avtr_trombi"/></a>
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>

					<em>il y a 2 jours</em>
					<p>
					Bonjour à tous<br/>
					Un peu fatiguée en ce moment mais on fait aller.<br/>
					Et vous ?</p>			
				</div>
			</div>
			
			<div id="bvrdg_312" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Georges">
					<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
					&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="avtr_trombi"/></a>
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>

					<em>il y a 2 jours</em>
					<p>
					Bonjour Jeanne<br/>
					On fait aller aussi<br/>
					mais avec l'hiver qui approche je pense qu'on est tous un peu diminué, surtout nous.
					Je crois que l'on est tous parti pour faire une cure de vitamine C.</p>			
				</div>
			</div>
			
			<div id="bvrdg_313" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Jeanne"><span><img src="/images/avtr_nnrs_red.png" class="sml_avtr"/>
					<img src="/images/aidant.png" title="Aidant"><font class="arial_b">Jeanne, Troyes (10000)</font><br/><p>
					<em>""</em></p>inscrit depuis le 30/06/09</span><img src="/images/avtr_nnrs_red.png" class="avtr_trombi"/></a>
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>

					<em>il y a 2 jours</em>
					<p><!-- attention une ligne il faut mettre des br pour compléter -->
					<p><br/><br/>
					Oui, excellente idée.
					<br/><br/><p>
					</p>			
				</div>
			</div>

			<div id="bvrdg_314" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Chrstophe"><span><img src="/images/avtr_rolreg.png" class="sml_avtr"/>
					<img src="/images/supporter.png" title="Supporter"><font class="arial_b">Christophe, Saint André les Vergers (10120)</font><br/><p>
					<em>""</em></p>inscrit depuis le 20/07/09</span><img src="/images/avtr_rolreg.png" class="avtr_trombi"/></a>
					
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>
					<em>hier</em>
					<p>
					Salut à tous,<br/>
					Tout à fait d'accord pour la vitamine C mais le magnesium cela compte aussi :)
					Du coup cure de chocolat obligatoire pour tout le monde.
					C'est dur quand même :D
					</p>			
				</div>
			</div>
			
			<div id="bvrdg_315" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Camille"><span><img src="/images/avtr_nnrs_green.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant"><font class="arial_b">Camille, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 25/06/09</span><img src="/images/avtr_nnrs_green.png" class="avtr_trombi"/></a>
					
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>
					<em>hier</em>
					<p>
					J'adhère complètement au recommandation de Christophe :)
					Merci
					</p>			
				</div>
			</div>
			
			<div id="bvrdg_316" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
						<a class="info_profil" href="#" title="Consulter la dernière contribution de Georges">
					<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
					&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="avtr_trombi"/></a>
					<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
					</div>
				
				
					<em>il y a 3 heures</em>
					<p>
					Bonjour tout le monde :)<br/>
					Alors comment cela va depuis le temps ?<br/>
					Je viens de répondre à Jeanne qui demandait de l'aide pour son mari qui ne boit pas assez d'eau mais je ne suis pas sur d'avoir complètement répondu à ce qu'elle disait...
					Si quelqu'un d'un peu plus expert se sent de compléter :)</p>			
				</div>
			</div>
			
			<div id="bvrdg_31_newcontrib" style="padding:2px;text-align:center;background:#DDD">
				
				<font class="arial_b">Participer à ce bavardage :</font><br/>
				<form>
					<p>Votre message : <br/>
					<textarea style="width:85%;height:90px;"></textarea><br/>
					<input type="submit" value="Envoyer"/></p>
				</form>
			</div>
		
		</div>
		
		<a href="javascript:void(0);" onClick="javascript:(document.getElementById('bvrdg_31_content').className == 'bvrdg_expanded')?changeStyle('bvrdg_31_content','bvrdg_minimized'):changeStyle('bvrdg_31_content','bvrdg_expanded');(document.getElementById('bvrdg_31_expander').className == 'bvrdg_expand')?changeStyle('bvrdg_31_expander','bvrdg_minimize'):changeStyle('bvrdg_31_expander','bvrdg_expand');"><div id="bvrdg_31_expander" class="bvrdg_expand">
			</div></a>
		
</div>
<!--
Second bavardage
-->
	<div id="bvrdg_32" style="background:#EEE;">
		
		<a name="id_bvrdg_32"></a>
		<div id="bvrdg_320" style="border-top:2px solid #CCC;border-bottom:2px solid #CCC;">
			<div style="padding:2px;width:72px;float:left;">
			
					<div class="f_left" style="padding-bottom:1px;">
		<a class="info_profil" href="#" title="Consulter la dernière contribution de Arno10">
		<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
		&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="sml_avtr"/></a></div> 
		<div class="f_left" style="padding-bottom:1px;">
		<a class="info_profil" href="#" title="Consulter la dernière contribution de Chrstophe"><span><img src="/images/avtr_rolreg.png" class="sml_avtr"/>
		<img src="/images/supporter.png" title="Supporter"><font class="arial_b">Christophe, Saint André les Vergers (10120)</font><br/><p>
		<em>""</em></p>inscrit depuis le 20/07/09</span><img src="/images/avtr_rolreg.png" class="sml_avtr"/></a></div>
		<div class="f_left" style="padding-bottom:1px;">
		<a class="info_profil" href="#" title="Consulter la dernière contribution de RPM"><span><img src="/images/avtr_rpm.png" class="sml_avtr"/><img src="/images/supporter.png" title="Supporter"><font class="arial_b">RPM, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 20/06/09</span><img src="/images/avtr_rpm.png" class="sml_avtr"/></a></div>
		<div class="f_left" style="padding-bottom:1px;">
		<a href="javascript:void(0);"><img src="/images/avtr_dummy.png" class="sml_avtr"/></a></div>
		
		</div>
		
		<div style="font-family:arial;padding:2px;height:95px;overflow:auto;">
		<div style="float:right;">
		<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
		</div>
		<font class="arial_b">Alors, quoi de neuf ?</font><br/>
		dernière contribution <br/>hier, de <a class="info_profil" href="#" title="Consulter la dernière contribution de Arno10">
		Arno10</a>
		<p>
		<a href="javascript:void(0);" onClick="javascript:(document.getElementById('bvrdg_32_content').className == 'bvrdg_expanded')?changeStyle('bvrdg_32_content','bvrdg_minimized'):changeStyle('bvrdg_32_content','bvrdg_expanded');(document.getElementById('bvrdg_32_expander').className == 'bvrdg_expand')?changeStyle('bvrdg_32_expander','bvrdg_minimize'):changeStyle('bvrdg_32_expander','bvrdg_expand');">Voir ce bavardage</a></p>
		</div>
		
	</div>

	<div id="bvrdg_32_content" class="bvrdg_minimized">
	
	<!-- reprise de l'expander pour simplifier le contrôle -->		
	<a href="javascript:void(0);" onClick="javascript:changeStyle('bvrdg_32_content','bvrdg_minimized');changeStyle('bvrdg_32_expander','bvrdg_expand');"><div id="bvrdg_32_expander_bis" class="bvrdg_minimize">
				</div></a>
			
		<div id="bvrdg_321" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
					<a class="info_profil" href="#" title="Consulter la dernière contribution de Georges">
				<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
				&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="avtr_trombi"/></a>
				<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
				</div>
				
					<em>il y a 2 jours</em>
					<p>
					Bonjour,<br/>
					On fait aller aussi<br/>
					mais avec l'hiver qui approche je pense qu'on est tous un peu diminué, surtout nous.
					Je crois que l'on est tous parti pour faire une cure de vitamine C.</p>			
				</div>
		</div>

		<div id="bvrdg_322" class="bvrdg_contrib">
				<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
				<a class="info_profil" href="#" title="Consulter la dernière contribution de Chrstophe"><span><img src="/images/avtr_rolreg.png" class="sml_avtr"/>
			<img src="/images/supporter.png" title="Supporter"><font class="arial_b">Christophe, Saint André les Vergers (10120)</font><br/><p>
			<em>""</em></p>inscrit depuis le 20/07/09</span><img src="/images/avtr_rolreg.png" class="avtr_trombi"/></a>
			
			<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
			</div>

				<em>hier</em>
				<p>
				Salut à tous,<br/>
				Tout à fait d'accord pour la vitamine C mais le magnesium cela compte aussi :)
				Du coup cure de chocolat obligatoire pour tout le monde.
				C'est dur quand même :D
				</p>			
			</div>
		</div>
		
		<div id="bvrdg_323" class="bvrdg_contrib">
			<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
				<a class="info_profil" href="#" title="Consulter la dernière contribution de RPM"><span><img src="/images/avtr_rpm.png" class="sml_avtr"/><img src="/images/supporter.png" title="Supporter"><font class="arial_b">RPM, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 25/06/09</span><img src="/images/avtr_rpm.png" class="avtr_trombi"/></a>
			
			<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
			</div>

				<em>hier</em>
				
				<p>
				J'adhère complètement au recommandation de Christophe :)
				Merci
				</p>
				
			</div>
		</div>
		
		<div id="bvrdg_324" class="bvrdg_contrib">
			<div class="bvrdg_contrib_content">
					<div class="bvrdg_contrib_author">
				<a class="info_profil" href="#" title="Consulter la dernière contribution de Georges">
			<span><font class="arial_b"><img src="/images/avtr_oeuf.png" class="sml_avtr"/><img src="/images/aidant.png" title="Aidant">
			&nbsp;Arno10, Troyes (10000)</font><br/><p><em>""</em></p>inscrit depuis le 26/06/09</span><img src="/images/avtr_oeuf.png" class="avtr_trombi"/></a>
			<a href="javascript:popup('favPopUp');" title="Marquer comme favoris" class="fav_set"></a>
			</div>
			
				<em>il y a 3 heures</em>
				<p>
				Bonjour tout le monde :)<br/>
				Alors comment cela va depuis le temps ?<br/>
				Je viens de répondre à Jeanne mais je ne suis pas sur d'avoir complètement répondu à ce qu'elle disait...
				Si quelqu'un d'un peu plus expert se sent de compléter :)</p>			
			</div>
		</div>
		
		<div id="bvrdg_32_newcontrib" style="padding:2px;text-align:center;background:#DDD">
			
			<font class="arial_b">Participer à ce bavardage :</font><br/>
			<form>
				<p>Votre message : <br/>
				<textarea style="width:85%;height:90px;"></textarea><br/>
				<input type="submit" value="Envoyer"/></p>
			</form>
		</div>
	
	</div>
	
	<a href="javascript:void(0);" onClick="javascript:(document.getElementById('bvrdg_32_content').className == 'bvrdg_expanded')?changeStyle('bvrdg_32_content','bvrdg_minimized'):changeStyle('bvrdg_32_content','bvrdg_expanded');(document.getElementById('bvrdg_32_expander').className == 'bvrdg_expand')?changeStyle('bvrdg_32_expander','bvrdg_minimize'):changeStyle('bvrdg_32_expander','bvrdg_expand');"><div id="bvrdg_32_expander" class="bvrdg_expand">
		</div></a>
	
</div>
<!-- fin du  bavardage id:32 -->

<!--
-->	


</div>
<div id="new_bvrdg" style="margin-top:15px">
<form>
<h4><img src="/images/evt_newcontrib.png">Lancer un nouveau bavardage <br/>sur cette page</h4>
<p>
Titre : <input/><br/>
Message : <br/>
<textarea style="width:95%;height:90px;"></textarea><br/>
<input type="submit" value="Envoyer"/>
<p>
</form>
</div>


</div>

<div>