<div style="padding: 0px 30px 30px 30px;">
<h3>A faire...</h3>
<div class="lrgspc"></div>
<p>
Cette page n'a pas encore été réalisée par l'équipe. N'hésitez pas à repasser plus tard.
</p>

<p>
<a href="<?php 
$visitor = new Zend_Session_Namespace('visiteur');
echo ($visitor->precedingUrl == null)?"/":$visitor->precedingUrl; 
?>">
Retour
</a></p>

<div class="lrgspc"></div>
<div class="lrgspc"></div>
<div class="lrgspc"></div>
</div>