<div style="padding: 0px 30px 30px 30px;">
	<h3>Confidentialité et données personnelles</h3>
	<p>
	Conformément à la loi « Informatique et Libertés » du 6 janvier 1978, les membres d'Aloa disposent d’un droit d’accès, de modification, de rectification et de suppression des données les concernant, sur demande écrite adressée à : </p><blockquote>Aloa - ICD/Tech-CICO, Université de Technologie de Troyes, 12, rue Marie Curie, BP 2060, 10010 TROYES CEDEX </blockquote><p>ou par mail à : </p><blockquote>matthieu.tixier {remplacer par un arobase} utt.fr</blockquote>

	
</div>




