<div style="padding: 0px 30px 30px 30px;">
	<h3>A propos d'Aloa</h3>
	<p>
	Aloa est le fruit de la coopération entre <a href="http://www.r-p-m.fr/" target="_blank">RéGéMa</a>, Réseau Gérontologie et Mémoire de l'Aube, et du laboratoire de recherche <a href="http://tech-cico.utt.fr/fr/index.html" target="_blank">ICD:Tech-CICO</a> avec le soutien du <a href="http://www.cg-aube.com/" target="_blank">Conseil Général de l'Aube</a> et de <a href="http://www.utt.fr/" target="_blank">l'Universtié de Technologie de Troyes</a>. </p>
	<p>
	Vous pouvez nous contacter pour toutes questions à l'adresse suivante : <blockquote>tixier.m {remplacer par un arobase} voila.fr</blockquote></p>
	</p>

</div>




