<div id="header">
	<div id="header_partner">
		<a href="http://tech-cico.utt.fr/fr/" target="_blank"><img class="logo_link" src="/images/tech-cico.png"></a>
		<a href="http://www.r-p-m.fr/" target="_blank"><img class="logo_link" src="/images/mini_logo_regema.jpg"></a>
		<a href="http://www.cg-aube.com/" target="_blank"><img class="logo_link" src="/images/cga.png"></a>
	</div>
<a title="Retourner à la page d'accueil" href="<?php echo $this->url(array('controller'=>'index'),'default',true); ?>"><img id="logo" class="logo_link" src="/images/logo.png"></a>
</div>
